# Generated by Django 4.0.6 on 2022-09-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='dateOfEmployment',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ التعيين'),
        ),
    ]
