# Generated by Django 4.0.6 on 2022-09-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_stock_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='department',
            field=models.CharField(db_column='another_name', default='', max_length=100),
            preserve_default=False,
        ),
    ]
