# Generated by Django 4.0.6 on 2022-09-22 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_type_service_typee_service_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('addressArea', models.CharField(blank=True, max_length=50, null=True)),
                ('addressBuilding', models.CharField(blank=True, help_text='تفاصيل العمارة السكنية', max_length=50, null=True)),
                ('addressApartment', models.CharField(blank=True, help_text='تفاصيل الشقه', max_length=50, null=True)),
                ('addressDetails', models.CharField(blank=True, help_text='اى تفاصيل إخرى للعنوان', max_length=50, null=True)),
                ('CNum', models.IntegerField(blank=True, null=True, unique=True, verbose_name='الرقم التعريفى')),
                ('notes', models.TextField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='notes',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='departement',
            name='notes',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='notes',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='notes',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('serialNum', models.IntegerField(blank=True, help_text='رقم سريال متفرد لكل تعاقد', null=True, unique=True)),
                ('notes', models.TextField(blank=True, max_length=50, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='store.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='store.employee')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.employee')),
                ('services', models.ManyToManyField(related_name='services', to='store.service')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
