# Generated by Django 4.0.6 on 2022-09-22 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_client_attendance_notes_departement_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
    ]
