# Generated by Django 4.0.6 on 2022-09-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created',
        ),
        migrations.AddField(
            model_name='product',
            name='createdTime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='lastTimeupdated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
