# Generated by Django 4.0.6 on 2022-09-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_client_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='employee',
        ),
        migrations.AddField(
            model_name='attendance',
            name='employee',
            field=models.ManyToManyField(related_name='Employees', to='store.employee'),
        ),
    ]
