# Generated by Django 4.0.6 on 2022-09-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_product_created_product_createdtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='createdTime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='time created'),
        ),
        migrations.AlterField(
            model_name='product',
            name='lastTimeupdated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='last time modified'),
        ),
    ]
