# Generated by Django 4.0.6 on 2022-09-24 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_attendance_employee_attendance_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='CNum',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='الرقم التعريفى'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_client', to='store.client'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_employee', to='store.employee'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='serialNum',
            field=models.IntegerField(blank=True, db_index=True, help_text='رقم سريال متفرد لكل تعاقد', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='eNum',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='الرقم التعريفى'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('content', models.CharField(blank=True, max_length=200, null=True, verbose_name='محتوى الاشعار')),
                ('Notification_date', models.DateField(blank=True, null=True)),
                ('viewed_Date', models.DateField(blank=True, null=True)),
                ('statue', models.IntegerField(blank=True, choices=[(1, 'Alert has not been viewed'), (2, 'Alert is viewed already by the employee')], db_index=True, default=1, null=True)),
                ('created_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note_employee_rquired', to='store.employee', verbose_name='اشعار موجه لـــ')),
                ('viewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note_employee_viewed', to='store.employee', verbose_name='تم اغلاق الاشعار بواسطة ')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FollowContractServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('startingDate', models.DateField(blank=True, null=True)),
                ('collcetStatus', models.CharField(blank=True, choices=[('تم الدفع', 'Service has been paid already'), ('مطلوب الدفع', 'Payment required for the service'), ('فى انتظار ميعاد التحصيل', 'Waiting for collection date')], default='فى انتظار ميعاد التحصيل', max_length=50, null=True)),
                ('collcetStatusNums', models.IntegerField(blank=True, choices=[('تم الدفع', 'Service has been paid already'), ('مطلوب الدفع', 'Payment required for the service'), ('فى انتظار ميعاد التحصيل', 'Waiting for collection date')], db_index=True, default='فى انتظار ميعاد التحصيل', null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='store.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='store.employee')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.employee')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service', to='store.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('content', models.CharField(blank=True, max_length=200, null=True, verbose_name='محتوى التنبيه')),
                ('alert_date', models.DateField(blank=True, null=True)),
                ('viewed_Date', models.DateField(blank=True, null=True)),
                ('statue', models.IntegerField(blank=True, choices=[(1, 'Alert has not been viewed'), (2, 'Alert is viewed already by the employee')], db_index=True, default=1, null=True)),
                ('created_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_employee_rquired', to='store.employee', verbose_name='تنبيه موج للموظف')),
                ('viewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_employee_viewed', to='store.employee', verbose_name='تم اغلاق التنبه بواسطة ')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
