# Generated by Django 4.0.6 on 2022-09-24 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_client_cnum_alter_contract_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ التنبيه'),
        ),
    ]
