# Generated by Django 4.0.6 on 2022-09-24 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_alert_alert_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followcontractservices',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service', to='store.service'),
        ),
    ]
