# Generated by Django 4.0.6 on 2022-09-24 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_followcontractservices_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='created_at_Date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='updated_at_Date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='created_at_Date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='updated_at_Date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='created_at_Date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='updated_at_Date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='created_at_Date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='updated_at_Date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='departement',
            name='created_at_Date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='departement',
            name='updated_at_Date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='created_at_Date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='updated_at_Date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='followcontractservices',
            name='created_at_Date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='followcontractservices',
            name='updated_at_Date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='created_at_Date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='updated_at_Date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='created_at_Date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='fixedPriceCollectDate_more',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='updated_at_Date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
