# Generated by Django 4.0.6 on 2022-09-24 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_followcontractservices_collcetstatusnums'),
    ]

    operations = [
        migrations.AddField(
            model_name='followcontractservices',
            name='collected_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='المبلغ الذى تم تحصيله'),
        ),
        migrations.AddField(
            model_name='followcontractservices',
            name='remain_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='المبلغ المتبقى'),
        ),
        migrations.AddField(
            model_name='followcontractservices',
            name='total_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='المبلغ المطلوب تحصيله'),
        ),
    ]
