# Generated by Django 4.0.6 on 2022-09-24 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_followcontractservices_collcetstatusnums'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followcontractservices',
            name='collcetStatusNums',
            field=models.IntegerField(blank=True, choices=[(1, 'Service has been paid already'), (2, 'Payment required for the service'), (3, 'Waiting for collection date')], db_index=True, default=3, null=True),
        ),
    ]
