# Generated by Django 4.0.6 on 2022-09-24 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_followcontractservices_collcetstatusnums'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='created_at_Date',
            new_name='created_at_date',
        ),
        migrations.RenameField(
            model_name='alert',
            old_name='updated_at_Date',
            new_name='updated_at_date',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='created_at_Date',
            new_name='created_at_date',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='updated_at_Date',
            new_name='updated_at_date',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='created_at_Date',
            new_name='created_at_date',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='updated_at_Date',
            new_name='updated_at_date',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='created_at_Date',
            new_name='created_at_date',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='updated_at_Date',
            new_name='updated_at_date',
        ),
        migrations.RenameField(
            model_name='departement',
            old_name='created_at_Date',
            new_name='created_at_date',
        ),
        migrations.RenameField(
            model_name='departement',
            old_name='updated_at_Date',
            new_name='updated_at_date',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='created_at_Date',
            new_name='created_at_date',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='updated_at_Date',
            new_name='updated_at_date',
        ),
        migrations.RenameField(
            model_name='followcontractservices',
            old_name='created_at_Date',
            new_name='created_at_date',
        ),
        migrations.RenameField(
            model_name='followcontractservices',
            old_name='updated_at_Date',
            new_name='updated_at_date',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='created_at_Date',
            new_name='created_at_date',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='updated_at_Date',
            new_name='updated_at_date',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='created_at_Date',
            new_name='created_at_date',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='updated_at_Date',
            new_name='updated_at_date',
        ),
    ]
