# Generated by Django 4.0.6 on 2022-09-24 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_rename_created_at_date_alert_created_at_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='followcontractservices',
            name='serviceDueDate',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ اداء الخدمه'),
        ),
    ]
